// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestApi;

#nullable disable

namespace TestApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TestApi.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Ricardo C.",
                            CreatedAt = new DateTime(2023, 7, 17, 20, 5, 33, 766, DateTimeKind.Local).AddTicks(3400),
                            Description = "Descripción UwU",
                            Title = "Holi"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Ricardo C.",
                            CreatedAt = new DateTime(2023, 7, 17, 20, 5, 33, 766, DateTimeKind.Local).AddTicks(3418),
                            Description = "Bar",
                            Title = "Foo"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Ricardo C.",
                            CreatedAt = new DateTime(2023, 7, 17, 20, 5, 33, 766, DateTimeKind.Local).AddTicks(3419),
                            Description = "l wea fme wn",
                            Title = "Causa pe"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
